// src/cc/CcInteractiveGrid.vue
<template>
  <svg
    :width="cellWidth * columns"
    :height="cellHeight * rows"
    class="absolute inset-0 h-full w-full border border-white/25"
    aria-hidden="true"
  >
    <rect
      v-for="cell in cells"
      :key="cell.index"
      :x="cell.x"
      :y="cell.y"
      :width="cellWidth"
      :height="cellHeight"
      class="stroke-white/20 transition-all duration-200"
      :class="hoveredIndex === cell.index ? 'fill-white/20' : 'fill-transparent'"
      @mouseenter="hoveredIndex = cell.index"
      @mouseleave="hoveredIndex = -1"
    />
  </svg>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'

const cellWidth = 44
const cellHeight = 44
const columns = 24
const rows = 24
const hoveredIndex = ref(-1)

const cells = computed(() => {
  const result: Array<{ index: number; x: number; y: number }> = []
  const total = columns * rows
  for (let index = 0; index < total; index++) {
    const x = (index % columns) * cellWidth
    const y = Math.floor(index / columns) * cellHeight
    result.push({ index, x, y })
  }
  return result
})
</script>

// src/react/cc/CcInteractiveGrid.tsx
import { useMemo, useState } from 'react'

export function CcInteractiveGrid({ cellSize = 64, className = '' }: { cellSize?: number; className?: string }) {
  const cellWidth = cellSize
  const cellHeight = cellSize
  const columns = 16
  const rows = 16
  const [hoveredIndex, setHoveredIndex] = useState(-1)

  const cells = useMemo(() => {
    const result: Array<{ index: number; x: number; y: number }> = []
    const total = columns * rows
    for (let index = 0; index < total; index += 1) {
      const x = (index % columns) * cellWidth
      const y = Math.floor(index / columns) * cellHeight
      result.push({ index, x, y })
    }
    return result
  }, [cellHeight, cellWidth])

  return (
    <svg width={cellWidth * columns} height={cellHeight * rows} className={`absolute inset-0 h-full w-full border border-white/25 ${className}`} aria-hidden="true">
      {cells.map((cell) => (
        <rect
          key={cell.index}
          x={cell.x}
          y={cell.y}
          width={cellWidth}
          height={cellHeight}
          className="stroke-white/25 transition-all duration-150"
          fill={hoveredIndex === cell.index ? 'rgba(255,255,255,0.2)' : 'transparent'}
          onMouseEnter={() => setHoveredIndex(cell.index)}
          onMouseLeave={() => setHoveredIndex(-1)}
        />
      ))}
    </svg>
  )
}
